# Generated by Django 6.1 on 2026-09-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='backlogs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
