# Generated by Django 6.0.6 on 2026-09-19 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('LEETCODE', 'LeetCode'), ('HACKERRANK', 'HackerRank'), ('CODECHEF', 'CodeChef'), ('CODEFORCES', 'Codeforces'), ('GEEKSFORGEEKS', 'GeeksforGeeks'), ('OTHER', 'Other')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('topic', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('problem_url', models.URLField(blank=True)),
                ('solved_independently', models.BooleanField(default=True)),
                ('solved_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solved_at', '-created_at'],
                'indexes': [models.Index(fields=['student', 'solved_at'], name='coding_prog_student_ec618a_idx'), models.Index(fields=['student', 'platform'], name='coding_prog_student_03188f_idx'), models.Index(fields=['student', 'difficulty'], name='coding_prog_student_64bd89_idx'), models.Index(fields=['student', 'topic'], name='coding_prog_student_448bd6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('title', ''), _negated=True), fields=('student', 'platform', 'title', 'solved_at'), name='unique_coding_problem_record')],
            },
        ),
    ]
