# Generated by Django 6.1 on 2026-09-25 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingproblem',
            name='solved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='codingproblem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codingproblem',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
