# Generated by Django 6.1 on 2026-09-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('eligible_branches', models.TextField(blank=True)),
                ('required_skills', models.TextField(blank=True)),
                ('minimum_backlogs', models.PositiveIntegerField(default=0)),
                ('package_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('job_role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
