# Generated by Django 6.1 on 2026-09-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='minimum_backlogs',
            new_name='maximum_backlogs',
        ),
    ]
