# Generated by Django 6.0.6 on 2026-10-06 04:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('QUANTITATIVE', 'Quantitative'), ('LOGICAL', 'Logical'), ('VERBAL', 'Verbal')], max_length=20, null=True)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('unanswered', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AptitudeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('QUANTITATIVE', 'Quantitative'), ('LOGICAL', 'Logical'), ('VERBAL', 'Verbal')], max_length=20)),
                ('topic', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('marks', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='aptitude_ap_categor_8ab5fb_idx'), models.Index(fields=['topic'], name='aptitude_ap_topic_164d63_idx'), models.Index(fields=['difficulty'], name='aptitude_ap_difficu_8bc313_idx'), models.Index(fields=['is_active'], name='aptitude_ap_is_acti_ed9100_idx'), models.Index(fields=['category', 'difficulty'], name='aptitude_ap_categor_a22aad_idx'), models.Index(fields=['is_active', 'category'], name='aptitude_ap_is_acti_9111a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AptitudeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='aptitude.aptitudeattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_answers', to='aptitude.aptitudequestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='aptitudeattempt',
            index=models.Index(fields=['student', 'created_at'], name='aptitude_ap_student_b855c6_idx'),
        ),
        migrations.AddIndex(
            model_name='aptitudeattempt',
            index=models.Index(fields=['student', 'category'], name='aptitude_ap_student_30a330_idx'),
        ),
        migrations.AddIndex(
            model_name='aptitudeattempt',
            index=models.Index(fields=['student', 'difficulty'], name='aptitude_ap_student_7067db_idx'),
        ),
        migrations.AddIndex(
            model_name='aptitudeanswer',
            index=models.Index(fields=['attempt'], name='aptitude_ap_attempt_17ad2b_idx'),
        ),
        migrations.AddIndex(
            model_name='aptitudeanswer',
            index=models.Index(fields=['question'], name='aptitude_ap_questio_5a5d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='aptitudeanswer',
            index=models.Index(fields=['attempt', 'question'], name='aptitude_ap_attempt_28fe0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='aptitudeanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_question_per_attempt'),
        ),
    ]
